name: 'TypeScript Error Reporter'
description: 'Report type check result on PR diff view.'
author: 'andoshin11'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  project:
    description: 'Optional project path.'
    required: false
  error_fail_threshold:
    description: 'Optional number of errors threshold at which this step fails.'
    required: false
  repo_token:
    description: 'Token to upload annotations to github api. Otherwise will max out at 10 error and 10 warning annotations'
    required: false
  
